config/routes.rb
Rails.application.routes.draw do

  resources :categories
  root 'posts#index'

  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  resources :users, except: [:new]

  get 'signup', to: 'users#new', as: :signup
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'

  resources :posts, except: [:index], path: "/"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home', to: 'welcome#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post_categories
    has_many :posts, through: :post_categories

    validates :name, presence: true, uniqueness: true, length: { in: 3..25 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :content, presence: true, length: { in: 10..300 }
  validates :user, presence: true
end

app/models/post_category.rb
class PostCategory < ApplicationRecord

    belongs_to :post
    belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, presence: true, length: { in: 3..25 }, uniqueness: { case_sensitive: false }
    validates :age, presence: true , numericality: { only_integer: true, greater_than_or_equal_to: 18 }
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 100 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end 

    def require_login
        if !logged_in?
            redirect_to root_path, notice: "You must login First"
        end
    end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end

  end

  private 

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_login, except: %i[index show]
  before_action :require_owner, only: %i[update edit destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, category_ids: [])
    end

    def require_owner
      if current_user != @post.user
        redirect_to posts_path, notice: "You are Not authorized"
      end
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in Congrates!"
      redirect_to user_path(user)
    else
      flash[:danger] = "Wrong Credentials!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  # before_action :require_login, except: %i[index show]
  before_action :require_owner, only: %i[update edit]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :password, :email.downcase)
    end

    def require_owner
      if current_user != @user
        redirect_to users_path, notice: "You are Not authorized"
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, opts = {size: 50})
        hash = Digest::MD5.hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{hash}?s=#{opts[:size]}"
        image_tag(gravatar_url, alt: user.name, class: "img-circle")
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

<% @categories.each.with_index(1) do |obj, index| %>

    <tr>
    <td scope="row"><%= index %> - </td>
    <td><%= link_to "#{obj.name}", obj, class: "btn-sm btn-danger" %></td>
    </tr>

<% end %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

<%= form_with(model: @category) do |form| %> 
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @category.errors.each do |error| %>
          <li class="panel-error"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control m-2"%>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <% if logged_in? %>
        <div class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link active btn" %>
        </div>
      <% else %>
        <div class="nav-item">
            <%= link_to 'Login', login_path, class: "btn" %>
        </div>
        <div class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav.html.erb' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %> 
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 10, class: "form-control m-2"%>
  </div>

  <div class="field form-group">
    <%= form.label :Categories %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "form-check-label mx-1")  {cb.check_box(class: "form-check-input mx-3") + cb.text} %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<% objs.each.with_index(1) do |obj, index| %>

    <tr>
        <td scope="row"><%= index %></td>
        <td><%= obj.content %></td>
        <td><%= obj.user.name %></td>
    <td><%= link_to 'Show', obj, class: "btn-sm btn-info" %></td>
    <% if logged_in? %>
    <% if current_user == obj.user || current_user.is_admin? %>
        <td><%= link_to 'Edit', edit_post_path(obj), class: "btn-sm btn-primary" %></td>
        <td><%= link_to 'Destroy', obj, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger" %></td>
    <% else %>
        <td></td>
        <td></td>
    <% end %>
    <% end %>   
    </tr>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Content</th>
      <th scope="col">User</th>
      <% if logged_in? %>
        <th></th>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <%= render 'list', objs: @posts %>
  </tbody>
</table>
<div class="pagination text-center">
  <%= will_paginate @posts, list_classes: %w(pagination justify-content-end) %>
</div>

<br>
<% if logged_in? %>
<%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="wrapper">
  <p> 
    <h6>Content</h6>
    <%= @post.content %>
  </p>

  <p>
    <h6>User</h6>
    <%= gravatar_for @post.user %>
    <%= @post.user.name %>
  </p>
  <small><%= time_ago_in_words(@post.created_at) %> ago</small>
</div>

<%= link_to 'Edit', edit_post_path(@post), class: "btn-sm btn-success m-3 p-2" %>
<%= link_to 'Back', root_path, class: "btn-sm btn-info m-3 p-2" %>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<%= form_with(scope: :session, url: login_path) do |f| %>

    <%= f.label :username, class: ' mt-3' %>
    <%= f.text_field :username, class: 'form-control mt-3' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control mt-3' %>

    <%= f.submit 'Login', class: "btn btn-primary btn-lg btn-block form-control mt-3" %>

<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, class: 'mb-2' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :age, class: 'mb-2' %>
    <%= form.number_field :age, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :password, class: 'mb-2' %>
    <%= form.text_field :password, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :email, class: 'mb-2' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= form.submit 'Create User', class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
    <% if current_user == user || current_user.is_admin? %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% end %>
    <% if current_user.is_admin? %>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<h1 class="m-5">Sign Up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<% if current_user == @user || current_user.is_admin? %>
  <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>
<%= link_to 'Back', users_path %>

app/views/welcome/home.html.erb
<h1>Thank God</h1>